spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
server:
  port: 8000
  error:
    include-stacktrace: never

